package entite;
// Generated 18 mars 2017 23:47:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name="agenda"
    ,catalog="agenda2017"
)
public class Agenda  implements java.io.Serializable {


     private Integer idAgenda;
     private User user;
     private String type;
     private Set<Partage> partages = new HashSet<Partage>(0);
     private Set<Evenement> evenements = new HashSet<Evenement>(0);

    public Agenda() {
    }

	
    public Agenda(User user, String type) {
        this.user = user;
        this.type = type;
    }
    public Agenda(User user, String type, Set<Partage> partages, Set<Evenement> evenements) {
       this.user = user;
       this.type = type;
       this.partages = partages;
       this.evenements = evenements;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_agenda", unique=true, nullable=false)
    public Integer getIdAgenda() {
        return this.idAgenda;
    }
    
    public void setIdAgenda(Integer idAgenda) {
        this.idAgenda = idAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="type", nullable=false, length=4)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agenda")
    public Set<Partage> getPartages() {
        return this.partages;
    }
    
    public void setPartages(Set<Partage> partages) {
        this.partages = partages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agenda")
    public Set<Evenement> getEvenements() {
        return this.evenements;
    }
    
    public void setEvenements(Set<Evenement> evenements) {
        this.evenements = evenements;
    }




}


