package entite;
// Generated 18 mars 2017 23:47:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partage generated by hbm2java
 */
@Entity
@Table(name="partage"
    ,catalog="agenda2017"
)
public class Partage  implements java.io.Serializable {


     private Integer idPartage;
     private Agenda agenda;
     private User user;

    public Partage() {
    }

    public Partage(Agenda agenda, User user) {
       this.agenda = agenda;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_partage", unique=true, nullable=false)
    public Integer getIdPartage() {
        return this.idPartage;
    }
    
    public void setIdPartage(Integer idPartage) {
        this.idPartage = idPartage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_agenda", nullable=false)
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


